/**
 * Authentication provider types.
 * Providers are admin-controlled — the backend is the source of truth.
 */

export type AuthProviderType = 'local' | 'google' | 'github' | 'microsoft' | 'bankid';

export interface AuthProviderConfig {
  type: AuthProviderType;
  enabled: boolean;
  displayName: string;
  icon?: string;
  /** Login identifiers supported by this provider */
  supportedIdentifiers: ('email' | 'username' | 'mobile')[];
  /** Provider-specific settings (non-sensitive, frontend-safe) */
  settings: Record<string, unknown>;
}

export interface OAuthProviderConfig extends AuthProviderConfig {
  type: 'google' | 'github' | 'microsoft';
  /** OAuth authorization URL (generated by backend) */
  authorizationUrl?: string;
}

export interface BankIdProviderConfig extends AuthProviderConfig {
  type: 'bankid';
  /** BankID environment */
  environment: 'test' | 'production';
}

export interface ProvidersResponse {
  providers: AuthProviderConfig[];
  branding: BrandingConfig;
}

export interface BrandingConfig {
  appName: string;
  logoUrl?: string;
  primaryColor?: string;
  accentColor?: string;
}
